---
title: "Epi 590R Final Project (Olympics)"
author: "Kourtney Ervin"
format: html
editor: visual
execute: 
  warning: false
  echo: false
---

## R Final Project - Kourtney Ervin

```{r}
#| label: Reading in Data
library(tidyverse)
library(here)
library(gtsummary)

medal_cols <- c("id", "name", "sex", "age", "height", "weight", "team", "NOC", "games",
								"year", "season", "city", "sport", "event", "medal")
medals <- read_csv(here::here("data", "raw","athlete_events.csv"),
									 skip = 1, col_names = medal_cols)
```

**Question 1** 

Creating a descriptive Table 1
```{r}
#| label: tbl-one
#| tbl-cap: "Descriptive Table"
tbl_summary(
	medals,
	by = sex,
	include = c(NOC, season, height, weight),
	label = list(
		NOC ~ "Country",
		season ~ "Summer/Winter",
		height ~ "Height",
		weight ~ "Weight"
	),
	missing_text = "Missing")|>
	add_p(test = list(all_continuous () ~ "t.test",
										all_categorical() ~ "chisq.test"))|>
	add_overall(col_label = "**Total**|>")|>
	bold_labels()|>
	modify_footnote(update = everything() ~ NA)|>
	modify_header(label = "**Variable**", p.value = "**P**")
```

@tbl-one is a descriptive table giving the distribution of countries, height, and weight of Olympic Athletes separated by sex and with a total column. 


**Question 2**

Fitting a regression model and creating the table
```{r}
#| label: tbl-two
#| tbl-cap: "Regression Table"
linear_mod <- lm(age ~ height + weight, data = medals)
tbl_regression(
	linear_mod,
	intercept = TRUE)
```


